### Agregar una nueva materia
POST http://localhost:8101/api/materias/agregar-materia HTTP/1.1
Content-Type: application/json

{
    "clave": "POO",
    "nombre": "Programación Orientada a Objetos",
    "descripcion": "Materia fundamental de programación orientada a objetos",
    "activo": 1
}
