PUT http://localhost:8101/api/materias/editar-materias/1 HTTP/1.1
Content-Type: application/json

{
    "clave": "DWI",
    "nombre": "Desarrollo Web Integral",
    "descripcion": "Materia de desarrollo web con spring boot y react"
}
